language: python
python: "3.8"
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "mysite"
  env: "mysite-env"
  bucket_name: "elasticbeanstalk-us-east-1-548482842996"
  on:
    branch: main
script:
  - echo "No tests yet"
after_deploy: "echo 'deployment has finished'"
